var photo_urls = {'American Sea Star': 'http://i.imgur.com/in1AvT1.png',
'Anemone Chime': 'http://i.imgur.com/xoWCxwd.jpg',
'Anemone Reef': 'http://i.imgur.com/lrPLDbR.jpg',
'Bleached Coral Reef': 'url',
'Blue Sea Jelly (free standing)': 'url',
'Brazillian Dragon Eel': 'url', 
'Ceiling Gyre': 'url',
'Chompers the Shark': 'http://i.imgur.com/DVAoEbI.jpg',
'Crashing Wave Diptych': 'url',
'Drum Kit': 'url',
'Flash the Marlin': 'http://i.imgur.com/AI66jWB.jpg',
'Flip Bite Fish #2': 'url',
'Flip Flop Fish #1': 'http://i.imgur.com/YdWTmTQ.jpg',
'Giant Anemone Reef': 'url',
'Giant Sea Jelly (hanging)': 'url',
'Giant Squid': 'url',
'Giant White & Red Jelly': 'url',
'Henry': 'url',
'Instrumental Eel': 'url',
'Lidia the Northern Fur Seal': 'url',
'Mask Collection': 'http://i.imgur.com/sh7dQYg.png',
'Musical Seaweed Tree': 'http://i.imgur.com/iJ6HBNG.jpg',
'Octavia the Octopus': 'http://i.imgur.com/KBCq7bz.jpg',
'Oil Spill': 'url',
'Orange Anemone': 'url',
'Penguin': 'http://i.imgur.com/zthS7lw.jpg',
'Photo Mosaic Panels (On The Beach and Art Supplies)': 'url',
'Polar Bear': 'url',
'Priscilla the Parrot Fish': 'http://i.imgur.com/yX6Z50t.jpg',
'Recycled Waves': 'url',
'River Otter': 'url',
'Rockhopper Penguin': 'http://i.imgur.com/cfCV1Qz.jpg',
'Rufus the Trigger Fish': 'http://i.imgur.com/Z1wB6tg.jpg',
'SBW mural': 'url',
'Sea Cave': 'url',
'Sea Jelly Bells': 'url',
'Sea Jelly Chimes (15)': 'http://i.imgur.com/xoWCxwd.jpg',
'Sea Lion Pup': 'url',
'Sea Star of Texas': 'url',
'Sebastian James the Tufted Puffin': 'url',
'SeeMore the Sea Lion Pup': 'http://i.imgur.com/EY4kuqP.jpg',
'Small Penguin': 'url',
'Stella Sea Horse': 'url',
'Styrofoam Drum Set': 'url',
'Sunset Beach': 'url',
'Tasha the Turtle on a Wave': 'url',
'Tropical Coral Reef': 'url',
'Tube Worm Ticklers': 'url',
'Whale Bone Rib Cage': 'http://i.imgur.com/zVhHHRW.png',
'Whale Bones': 'http://i.imgur.com/zVhHHRW.png',
'Whale Tail': 'url',
'Yellow Jelly': 'url',
'Yellow Orange Sea Jelly': 'url',
'Yellow Sea Jelly': 'url'}
