//var venueData = {'Shedd Aquarium':['shedd is great'],'Point Defiance Zoo & Aquarium':['Outdoor Sea Horse<br>Chompers the Shark<br>Turtle on a Wave<br>Parrot Fish<br>Octopus<br>Blue Free-Standing Sea Jelly<br>Lidia<br>Puffin<br>Penguin<Anemone Reef>']};

var venueData = {'Harbortown Event Center':[['<li>Musical Sea Star</li><li>Turtle on a Wave</li><li>Oil Spill</li><li>Coral Reef</li><li>Henry</li>'],[-124.4840,43.1190]],'Reiman Gardens':[['<li>Marlin</li><li>Rockhopper Penguin</li><li>American Sea Star</li><li>Polar Bear</li><li>Great White Shark</li><li>Whale Tail</li><li>Trigger Fish</li><li>Sea Lion Pup</li><li>Hanging Blue Jelly</li><li>15 Small Hanging Jellies</li>'],[-93.6386,42.0106]], 'Shedd Aquarium':[['<li>New River Otter</li><li>Dragon Eel</li><li>Stella Sea Horse</li><li>Hanging Blue Jelly</li><li>Sea Jelly Bloom</li><li>Tropical Coral Reef</li><li>Water Bottle Anemone</li><li>Flip Flop Fish #2</li><li>Fish Bite #2</li><li>Clown Fish on Anemone</li>'],[-87.6140, 41.8676]],'Point Defiance Zoo & Aquarium':[['<li>Outdoor Sea Horse</li><li>Chompers the Shark</li><li>Turtle on a Wave</li><li>Parrot Fish</li><li>Octopus</li><li>Blue Free-Standing Sea Jelly</li><li>Lidia</li><li>Puffin</li><li>Penguin</li><li>Anemone Reef</li>'],[-122.5215, 47.3050]]};

var photo_urls = {'American Sea Star': 'http://i.imgur.com/in1AvT1.png',
'Anemone Chime': 'http://i.imgur.com/xoWCxwd.jpg',
'Anemone Reef': 'http://i.imgur.com/lrPLDbR.jpg',
'Bleached Coral Reef': 'url',
'Blue Sea Jelly (free standing)': 'url',
'Brazillian Dragon Eel': 'url', 
'Ceiling Gyre': 'url',
'Chompers the Shark': 'http://i.imgur.com/DVAoEbI.jpg',
'Crashing Wave Diptych': 'url',
'Drum Kit': 'url',
'Flash the Marlin': 'http://i.imgur.com/AI66jWB.jpg',
'Flip Bite Fish #2': 'url',
'Flip Flop Fish #1': 'http://i.imgur.com/YdWTmTQ.jpg',
'Giant Anemone Reef': 'url',
'Giant Sea Jelly (hanging)': 'url',
'Giant Squid': 'url',
'Giant White & Red Jelly': 'url',
'Henry': 'url',
'Instrumental Eel': 'url',
'Lidia the Northern Fur Seal': 'url',
'Mask Collection': 'http://i.imgur.com/sh7dQYg.png',
'Musical Seaweed Tree': 'http://i.imgur.com/iJ6HBNG.jpg',
'Octavia the Octopus': 'http://i.imgur.com/KBCq7bz.jpg',
'Oil Spill': 'url',
'Orange Anemone': 'url',
'Penguin': 'http://i.imgur.com/zthS7lw.jpg',
'Photo Mosaic Panels (On The Beach and Art Supplies)': 'url',
'Polar Bear': 'url',
'Priscilla the Parrot Fish': 'http://i.imgur.com/yX6Z50t.jpg',
'Recycled Waves': 'url',
'River Otter': 'url',
'Rockhopper Penguin': 'http://i.imgur.com/cfCV1Qz.jpg',
'Rufus the Trigger Fish': 'http://i.imgur.com/Z1wB6tg.jpg',
'SBW mural': 'url',
'Sea Cave': 'url',
'Sea Jelly Bells': 'url',
'Sea Jelly Chimes (15)': 'http://i.imgur.com/xoWCxwd.jpg',
'Sea Lion Pup': 'url',
'Sea Star of Texas': 'url',
'Sebastian James the Tufted Puffin': 'url',
'SeeMore the Sea Lion Pup': 'http://i.imgur.com/EY4kuqP.jpg',
'Small Penguin': 'url',
'Stella Sea Horse': 'url',
'Styrofoam Drum Set': 'url',
'Sunset Beach': 'url',
'Tasha the Turtle on a Wave': 'url',
'Tropical Coral Reef': 'url',
'Tube Worm Ticklers': 'url',
'Whale Bone Rib Cage': 'http://i.imgur.com/zVhHHRW.png',
'Whale Bones': 'http://i.imgur.com/zVhHHRW.png',
'Whale Tail': 'url',
'Yellow Jelly': 'url',
'Yellow Orange Sea Jelly': 'url',
'Yellow Sea Jelly': 'url'}
