// A Place to store venue and sculpture info

var venueData = {'Harbortown Event Center':[['<li>Musical Sea Star</li><li>Turtle in a Net</li><li>Oil Spill</li><li>Coral Reef</li><li>Henry</li>'],[-124.4840,43.1190],['<h1>Harbortown Event Center</h1><br><h2>Exhibit & Workshop Year-round: Th-Sun 11am-5pm</h2><br><h3>Learn More at <a href="http://www.washedashore.org/" target="_blank"><i>WashedAshore.org</a></h3>']],'Reiman Gardens':[['<li>Marlin</li><li>Rockhopper Penguin</li><li>American Sea Star</li><li>Polar Bear</li><li>Great White Shark</li><li>Whale Tail</li><li>Trigger Fish</li><li>Sea Lion Pup</li><li>Hanging Blue Jelly</li><li>Sea Jelly Bloom (15)</li>'],[-93.6386,42.0106],['<h1>Reiman Gardens</h1><br><h2>April 28th through October 31st 2017</h2><br><h3>Learn More at <a href="http://www.reimangardens.com/" target="_blank"><i>ReimanGardens.com</a></h3>']], 'Shedd Aquarium':[['<li>River Otter</li><li>Dragon Eel</li><li>Stella Sea Horse</li><li>Hanging Blue Jelly</li><li>Sea Jelly Bloom (15)</li><li>Tropical Coral Reef</li><li>Water Bottle Anemone</li><li>Flip Flop Fish #2</li><li>Fish Bite #2</li><li>Clown Fish on Anemone</li>'],[-87.6140, 41.8676],['<h1>Shedd Aquarium</h1><br><h2>September 23rd 2017 through September 23rd 2018</h2><br><h3>Learn More at <a href="www.sheddaquarium.org/" target="_blank"><i>SheddAquarium.org</a></h3>']],'Point Defiance Zoo & Aquarium':[['<li>Outdoor Sea Horse</li><li>Chompers the Shark</li><li>Turtle on a Wave</li><li>Priscilla the Parrot Fish</li><li>Octavia the Octopus</li><li>Blue Free-Standing Sea Jelly</li><li>Lidia the Northern Fur Seal</li><li>Tufted Puffin</li><li>Gertrude the Penguin</li><li>Anemone Reef</li>'],[-122.5215, 47.3050],['<h1>Point Defiance Zoo & Aquarium</h1><br><h2>April 21st through October 16th 2017</h2><br><h3>Learn More at <a href="www.pdza.org" target="_blank"><i>Pdza.org</a></h3>']],'Science Museum of Virginia':[['<li>Houston Sea Jelly (Blue Hanging)</li><li>Flip Flop Fish #2</li><li>Giant Anemone</li><li>Tropical Coral Reef</li><li>Eli the Eel</li><li>Musical Seaweed</li><li>Ocean Gyre</li><li>Whale Bone Rib Cage #2</li><li>Newport Sea Jelly (White & Red Jelly)</li><li>Georgia Sea Jelly (yellow)</li><li>Plastic Tribe</li><li>Workshop Gyre*</li><li>Styrofoam Coral Reef</li><li>Sunset Beach Mural</li><li>Tsunami Mural</li><li>Crashing Waves Mural</li><li>Recycled Waves Mural</li><li>Drum Kit</li><li>Newport Sea Jelly (White & Red Jelly)</li><li>Georgia Sea Jelly (yellow)</li>'],[-122.5215, 47.3050],['<h1>Science Museum of Virginia</h1><br><h2>March 4th through September 4th 2017</h2><br><h3>Learn More at <a href="www.smv.org/" target="_blank"><i>Smv.org</a></h3>']]}

var sculptureData = {'American Sea Star':[['photos/american_sea_star1.jpg'],[""]],
'Anemone Chime': 'http://i.imgur.com/xoWCxwd.jpg',
'Anemone Reef': [['photos/anemone_reef1.jpg'],[""]],
'Bleached Coral Reef': 'url',
'Blue Free-Standing Sea Jelly': [['photos/sea_jelly_15ft1.jpg'],[""]],
'Brazillian Dragon Eel': 'url', 
'Ceiling Gyre': 'url',
'Chompers the Shark': [['photos/chompers_the_shark1.jpg'],[""]],
'Clown Fish on Anemone':[['photos/clown_fish_on_anemone1.jpg'],[""]],
'Coral Reef':[['photos/coral_reef1.jpg'],[""]],
'Crashing Wave Diptych': 'url',
'Dragon Eel':[['photos/weedy_sea_dragon_with_environment1.jpg'],[""]],
'Drum Kit': 'url',
'Flash the Marlin': 'http://i.imgur.com/AI66jWB.jpg',
'Flip Flop Fish #1': [['photos/flip_flop_fish_wall1.jpg'],[""]],
'Flip Flop Fish #2': [['photos/flip_flop_fish_wall1.jpg'],[""]],
'Fish Bite #2': [['photos/fish_bite_fish_wall1.jpg'],[""]],
'Giant Anemone Reef': 'url',
'Giant Sea Jelly (hanging)': 'url',
'Giant Squid': 'url',
'Giant White & Red Jelly': 'url',
'Great White Shark':[['photos/great_white_shark1.jpg'],[""]],
'Hanging Blue Jelly':[['photos/oil_spill1.jpg'],[""]],
'Henry':[['photos/henry1.jpg'],[""]],
'Instrumental Eel': 'url',
'Lidia the Northern Fur Seal': [['photos/lidia1.jpg'],[""]],
'Mask Collection': 'http://i.imgur.com/sh7dQYg.png',
'Marlin':[['photos/marlin1.jpg'],[""]],
'Musical Seaweed Tree': 'http://i.imgur.com/iJ6HBNG.jpg',
'Musical Sea Star':[['photos/musical_sea_star1.jpg','photos/musical_sea_star2.jpg'],['There are over 2000 species of Sea Stars Worldwide']],
'Octavia the Octopus':[['photos/octopus1.jpg'],[""]],
'Oil Spill':[['photos/oil_spill1.jpg'],[""]],
'Outdoor Sea Horse':[['photos/stella_sea_horse2.jpg'],[""]],
'Orange Anemone': 'url',
'Priscilla the Parrot Fish':[['photos/parrot_fish1.jpg'],[""]],
'Gertrude the Penguin':[['photos/gertrude_the_penguin1.jpg'],[""]],
'Photo Mosaic Panels (On The Beach and Art Supplies)': 'url',
'Polar Bear':[['photos/polar_bear_on_melting_iceburg1.jpg'],[""]],
'Recycled Waves': 'url',
'River Otter': [['photos/river_otter1.jpg'],[""]],
'Rockhopper Penguin': [['photos/rockhopper_penguin1.jpg'],[""]],
'Rufus the Trigger Fish': 'http://i.imgur.com/Z1wB6tg.jpg',
'SBW mural': 'url',
'Sea Cave': 'url',
'Sea Jelly Bells': 'url',
'Sea Jelly Bloom (15)': [['photos/sea_jelly_bloom1.jpg'],[""]],
'Sea Lion Pup': [['photos/sea_lion_pup1.jpg'],[""]],
'Sea Star of Texas': 'url',
'Sebastian James the Tufted Puffin': 'url',
'SeeMore the Sea Lion Pup': 'http://i.imgur.com/EY4kuqP.jpg',
'Small Penguin': 'url',
'Stella Sea Horse': [['photos/stella_sea_horse1.jpg'],[""]],
'Styrofoam Drum Set': 'url',
'Sunset Beach': 'url',
'Tasha the Turtle on a Wave': 'url',
'Trigger Fish':[['photos/trigger_fish1.jpg'],[""]],
'Tropical Coral Reef': [['photos/tropical_coral_reef1.jpg'],[""]],
'Tube Worm Ticklers': 'url',
'Tufted Puffin':[['photos/tufted_puffin1.jpg'],[""]],
'Turtle in a Net':[['photos/Turtle_in_a_net1.jpg'],[""]],
'Turtle on a Wave':[['photos/turtle_on_a_wave2.jpg'],[""]],
'Water Bottle Anemone':[['photos/anemone_reef1.jpg'],[""]],
'Whale Bone Rib Cage': 'http://i.imgur.com/zVhHHRW.png',
'Whale Bones': 'http://i.imgur.com/zVhHHRW.png',
'Whale Tail':[['photos/whale_tail1.jpg'],[""]],
'Yellow Jelly': 'url',
'Yellow Orange Sea Jelly': 'url',
'Yellow Sea Jelly': 'url'}
